const API_TOKEN = 'YOUR_API_TOKEN';
const API_SECRET = 'YOUR_API_SECRET';
const DATACENTER = 'DATACENTER';
const BAM_API_TOKEN = 'YOUR_BAM_API_TOKEN';
const BAM_API_SECRET = 'YOUR_BAM_API_SECRET';
const BAM_DATACENTER = 'BAM_DATACENTER';
